name: Lint
on: [push, pull_request]

jobs:
  tfproviderlint:
    runs-on: ubuntu-latest
    container: bflad/tfproviderlint:0.19
    steps:
      - uses: actions/checkout@v2
      - run: |
          tfproviderlint \
            -c 1 \
            -AT001 \
            -AT002 \
            -S001 \
            -S002 \
            -S003 \
            -S004 \
            -S005 \
            -S007 \
            -S008 \
            -S009 \
            -S010 \
            -S011 \
            -S012 \
            -S013 \
            -S014 \
            -S015 \
            -S016 \
            -S017 \
            -S019 \
            ./...
